name: GitHub Actions Demo
on: [push]
jobs:
  main-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‘‹ A ${{ github.event_name }} event running on a ${{ runner.os }} server."
      - run: echo "ğŸ” The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner. And the workflow is now ready to test your code on the runner."
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.2.0'
      - run: echo "ğŸ“¦ Installing packages"
      - run: yarn install
      - run: echo "ğŸ–¥ï¸ Pre testing"
      - run: yarn deploy:test
      - run: echo "ğŸ–¥ï¸ Run e2e testing"
      - run: yarn deploy:e2e
      - run: echo "âœ… Congratulations!"
