name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
jobs:
  main-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üëã A ${{ github.event_name }} event running on a ${{ runner.os }} server."
      - run: echo "üîé The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.2.0'
      - run: echo "üì¶ Installing packages" && yarn install
      - name: Run echo "üñ•Ô∏è Run unit tests with coverage"
        run: |
          SUMMARY="$(yarn test --coverage --coverageReporters=text-summary | tail -3 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 49ff7044879e43a1daf430086b622c53
          filename: next-boilerplate__heads_main.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest
      - run: echo "üñ•Ô∏è Building" && yarn build --profile
      - run: echo "üñ•Ô∏è Run e2e testing" && yarn deploy:e2e
      - run: echo "‚úÖ Congratulations!"
